buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
        maven { url 'https://jcenter.bintray.com/' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
        maven { url 'https://jcenter.bintray.com/' }
        maven { url 'https://jitpack.io' }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
